-- =============================================================================
-- PARKING MANAGER DATABASE SCHEMA
-- Run this in Supabase SQL Editor to create parking tables
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. PARKING INVENTORY TABLE
-- Tracks all parking spots and their current assignments
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parking_inventory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    
    -- Spot Details
    property TEXT NOT NULL,
    spot_number TEXT NOT NULL,
    spot_type TEXT NOT NULL CHECK (spot_type IN ('Outdoor', 'Indoor', 'Covered', 'Garage')),
    
    -- Status: Open, Occupied, Pending Termination
    status TEXT NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'Occupied', 'Pending Termination')),
    
    -- Tenant Assignment (null if Open)
    tenant_name TEXT,
    unit_number TEXT,
    
    -- Vehicle Info
    vehicle_make TEXT,
    vehicle_model TEXT,
    vehicle_color TEXT,
    license_plate TEXT,
    
    -- Dates
    assigned_date DATE,
    termination_date DATE,  -- When spot will become available
    
    -- Fees
    monthly_rate DECIMAL(10,2) DEFAULT 0,
    
    -- Linked to Waitlist Entry (for automation)
    linked_waitlist_entry_id UUID REFERENCES waitlist_entries(id) ON DELETE SET NULL,
    
    -- Notes
    notes TEXT,
    
    -- Unique constraint: one spot per property
    UNIQUE(property, spot_number)
);

-- -----------------------------------------------------------------------------
-- 2. PARKING WAITLIST TABLE
-- Multi-tier waitlists: 1st Spot, 2nd Spot, Indoor Upgrade
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parking_waitlist (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    
    -- Tenant Info
    tenant_name TEXT NOT NULL,
    unit_number TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    
    -- Property
    property TEXT NOT NULL,
    
    -- Waitlist Type: 1st Spot, 2nd Spot, Indoor Upgrade
    waitlist_type TEXT NOT NULL CHECK (waitlist_type IN ('1st Spot', '2nd Spot', 'Indoor Upgrade')),
    
    -- Current spot (if upgrading or getting 2nd spot)
    current_spot_number TEXT,
    
    -- Preferred spot type
    preferred_spot_type TEXT CHECK (preferred_spot_type IN ('Outdoor', 'Indoor', 'Covered', 'Garage', 'Any')),
    
    -- Status
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Offered', 'Assigned', 'Cancelled')),
    
    -- Assignment tracking
    assigned_agent TEXT,
    offered_spot_id UUID REFERENCES parking_inventory(id) ON DELETE SET NULL,
    offered_date DATE,
    
    -- Priority (lower = higher priority, based on signup date)
    priority_order INTEGER,
    
    -- Notes
    notes TEXT
);

-- -----------------------------------------------------------------------------
-- 3. PARKING PERMITS TABLE
-- Track generated permits
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parking_permits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    
    -- Link to inventory
    parking_spot_id UUID NOT NULL REFERENCES parking_inventory(id) ON DELETE CASCADE,
    
    -- Permit Details (denormalized for historical record)
    property TEXT NOT NULL,
    spot_number TEXT NOT NULL,
    tenant_name TEXT NOT NULL,
    unit_number TEXT NOT NULL,
    vehicle_make TEXT,
    vehicle_model TEXT,
    license_plate TEXT,
    
    -- Validity
    issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expiration_date DATE,
    
    -- Permit number for display
    permit_number TEXT UNIQUE NOT NULL,
    
    -- Generated by
    generated_by TEXT
);

-- -----------------------------------------------------------------------------
-- 4. PARKING NOTIFICATIONS TABLE
-- Track sent notifications (prevent duplicates like notified_matches)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parking_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    
    parking_spot_id UUID NOT NULL REFERENCES parking_inventory(id) ON DELETE CASCADE,
    waitlist_entry_id UUID NOT NULL REFERENCES parking_waitlist(id) ON DELETE CASCADE,
    
    notification_type TEXT NOT NULL CHECK (notification_type IN ('spot_available', 'offer_sent', 'assignment_confirmed')),
    
    sent_to_email TEXT,
    sent_to_agent TEXT,
    
    UNIQUE(parking_spot_id, waitlist_entry_id, notification_type)
);

-- -----------------------------------------------------------------------------
-- 5. EXTEND ACTIVITY LOG FOR PARKING
-- Add parking-related action types
-- -----------------------------------------------------------------------------
-- Note: The existing activity_log table can be reused. 
-- We'll add a 'module' column to distinguish waitlist vs parking actions.

ALTER TABLE activity_log 
ADD COLUMN IF NOT EXISTS module TEXT DEFAULT 'waitlist' CHECK (module IN ('waitlist', 'parking'));

-- -----------------------------------------------------------------------------
-- 6. INDEXES FOR PERFORMANCE
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_parking_inventory_property ON parking_inventory(property);
CREATE INDEX IF NOT EXISTS idx_parking_inventory_status ON parking_inventory(status);
CREATE INDEX IF NOT EXISTS idx_parking_waitlist_property ON parking_waitlist(property);
CREATE INDEX IF NOT EXISTS idx_parking_waitlist_type ON parking_waitlist(waitlist_type);
CREATE INDEX IF NOT EXISTS idx_parking_waitlist_status ON parking_waitlist(status);

-- -----------------------------------------------------------------------------
-- 7. ROW LEVEL SECURITY (RLS)
-- -----------------------------------------------------------------------------
ALTER TABLE parking_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE parking_waitlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE parking_permits ENABLE ROW LEVEL SECURITY;
ALTER TABLE parking_notifications ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users full access (same as waitlist_entries)
CREATE POLICY "Allow authenticated users full access to parking_inventory"
ON parking_inventory FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated users full access to parking_waitlist"
ON parking_waitlist FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated users full access to parking_permits"
ON parking_permits FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated users full access to parking_notifications"
ON parking_notifications FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- 8. UPDATED_AT TRIGGER FUNCTION
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to parking tables
DROP TRIGGER IF EXISTS update_parking_inventory_updated_at ON parking_inventory;
CREATE TRIGGER update_parking_inventory_updated_at
    BEFORE UPDATE ON parking_inventory
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_parking_waitlist_updated_at ON parking_waitlist;
CREATE TRIGGER update_parking_waitlist_updated_at
    BEFORE UPDATE ON parking_waitlist
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
